import { Geist, Geist_Mono, Playfair_Display } from "next/font/google";
import "./globals.css";
import SmoothScroll from "./components/ui/SmoothScroll";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const PlayfairDisplay = Playfair_Display({
  variable: "--font-playfair-display",
  style: "italic",
});

export const metadata = {
  title: "Evergreen Lawn Care - Template",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      data-scroll-behavior="smooth"
      className={`${geistSans.variable} ${PlayfairDisplay.variable}`}
    >
      <body>
        {/* <ReactLenis /> */}
        <SmoothScroll />
        {children}
      </body>

     
    </html>
  );
}
